spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: homework2_withoutshiro
  redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 10000
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
      password:
  cache:
    ehcache:
      config:

server:
  compression:
    enabled: true
  port: 8080
  session:
    timeout: 3600
  tomcat:
    uri-encoding: UTF-8

hive:
  dev: true
  mongodb:
    host: ${spring.data.mongodb.host}
    port: ${spring.data.mongodb.port}
    database: ${spring.data.mongodb.database}
  exceptionsMap:
    101: "parameter invalid" #参数错误
    1011: "required parameter absent" #参数缺失
    1012: "username format error" #用户名不符合规则
    1013: "parameter duplicate" #参数重复
    1014: "password format error" #密码格式不正确
    1015: "confirm error" #确认密码和密码不同
    1016: "username not found" #用户名对应用户不存在
    1017: "wrong password" #密码不正确
    102: "authorization error" #权限错误


